# fly.toml app configuration file generated for aliar-car on 2026-06-03T19:41:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aliar-car'
primary_region = 'arn'

[build]
  dockerfile = 'Dockerfile'

[env]
  ASPNETCORE_ENVIRONMENT = 'Production'
  ASPNETCORE_FORWARDEDHEADERS_ENABLED = 'true'
  ASPNETCORE_URLS = 'http://0.0.0.0:8080'

[[mounts]]
  source = 'aliyar_uploads'
  destination = '/data/uploads'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '2m0s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
